# Generated by Django 3.2.22 on 2023-10-11 15:17

from django.db import migrations


def mark_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(mark_building)
    ]
