# Generated by Django 3.2.22 on 2023-10-11 15:17

from django.db import migrations


def mark_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= 2015
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(mark_building)
    ]
