# Generated by Django 3.2.22 on 2023-10-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20231011_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(verbose_name='Новостройка'),
        ),
    ]
