# Generated by Django 3.2.22 on 2023-10-13 13:31

from django.db import migrations
import phonenumbers


def purify_phones(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    for flat in Flat.objects.all():
        pure_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(pure_number):
            flat.owners_pure_phone = pure_number

        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(purify_phones)
    ]
