# Generated by Django 3.2.22 on 2023-10-14 18:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_flat_owners_pure_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('owners_phonenumber', models.CharField(max_length=20, verbose_name='номер владельца')),
                ('owners_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='нормализованный номер владельца')),
                ('owned_flats', models.ManyToManyField(related_name='flat_owners', to='property.Flat', verbose_name='квартиры в собственности')),
            ],
        ),
    ]
