# Generated by Django 3.2.22 on 2023-10-14 18:30

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    for flat in Flat.objects.all().iterator():
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owners_pure_phone=flat.owners_pure_phone,
        )
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owners)
    ]
