# Generated by Django 3.2.22 on 2023-10-15 13:10

from django.db import migrations


def fill_owners_with_flats(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    for owner in Owner.objects.all().iterator():
        flats = Flat.objects.filter(owner=owner.name, owners_phonenumber=owner.owners_phonenumber)
        owner.owned_flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20231015_1610'),
    ]

    operations = [
        migrations.RunPython(fill_owners_with_flats)
    ]
